apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-vayu-nginx
  labels:
    app: local-vayu-nginx
    release: local-vayu-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: local-vayu-nginx
  template:
    metadata:
      labels:
        app: local-vayu-nginx
    spec:
      containers:
        - name: vayu-nginx
          image: 'nginx:1.14.2'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: local-vayu-nginx-svc
spec:
  selector:
    app: local-vayu-nginx
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
